### ISSUE TITLE
Uncaught ReferenceError: asteroidImmutableMixin is not defined

### ISSUE THREAD

**Issue by naysumyat** [mondora/asteroid-immutable-collections-mixin#1]
I just copied example code provided and i am getting this error. 
Uncaught ReferenceError: asteroidImmutableMixin is not defined. 
when i use  createClass([immutableCollectionMixin]);  , the error is gone but cannot get collections.

**Comment by davidebianchi** [comment]
Hi @naysumyat,

thanks, I have fixed the mistake in the example! 👍 

The collections should be in the instance created with `asteroid`. Can you check if do you have `meteor` up and if is `asteroid` connected with this? Is `asteroid.collections` an `Immutable.Map()`?
