### ISSUE TITLE
Subscription doesn't return anything

### ISSUE THREAD

**Issue by Rebolon** [mondora/asteroid-immutable-collections-mixin#3]
Hi,

trying to subscribe to a collection/publication but nothing happen.
On client-side we need to do asteroid.subscribe("mycollection-name")
On server-side i did a "mycollection-name" publication with a log inside to check if it return something.

On server-side it seems to be ok, but on client-side, the Map has nothing inside...

**Comment by davidebianchi** [comment]
Hi @Rebolon,

if returns a `Map`, the mixin seems work fine.
Can you provide some snippet of your implementation?

**Comment by Rebolon** [comment]
Hi @davidebianchi,

In fact i did a mistake because i missed the fact that asteroid.subscribe returned an EventEmitter.
Now i do this
`
let subscription = asteroid.subscribe("myPublication");

let items;

subscription.ready(() => {
  items = asteroid.collections.get("myPublication");
});
`

and the items Map is filled,
sorry for all.
